### ISSUE TITLE
Use waitress instead of gunicorn to avoid database connection overload

### ISSUE THREAD

**Issue by etianen** [etianen/django-herokuapp#9]

**Comment by tilgovi** [comment]
Just ran into this while searching for something else. There is a `--worker-connections` setting that controls the concurrency of each worker.

**Comment by racitup** [comment]
So I'm not sure anyone will read this since it's closed but.. wondered if anyone had any advice on the number of waitress threads to use on the heroku free dyno type? I've bumped it to 16 (because you can have up to 256) but the database connection limit of 20 is reached quite quickly. I assumed there would be one connection per thread, but clearly not...
Incidentally I have enabled persistent db connections, not sure if that makes a difference.
It seems the default 4 threads causes a maximum of 5 db connections.

**Comment by etianen** [comment]
I'd keep it pretty low, something like 4.

Because waitress buffers incoming requests, actual request handling by a
thread should be very quick.

Not sure why you'd hit a database connection limit, unless maybe Django
isn't cleaning up connections property after use. Are you using persistent
connections?

**Comment by racitup** [comment]
Yes persistent connections.
I'm trying 12 threads which seems to work okay and db connections seem to stay at 12 or 13.
